### PR TITLE
adding support to float ZZ background

### PR DESCRIPTION
**Pull request by tjavaid**

### CODE REVIEW

**Comment by ram1123** [comment]
@tjavaid 

Please note the branch name. Our main branch is `CMSSW_10_X`. So make the pull request into that branch.

**Comment by vukasinmilosevic** [comment]
@tjavaid I see that there are 710 files changed. You didn't start from the CMS_10_X branch as base but instead started from some really old version. Can you please open a new PR, starting from CMS_10_X with your additions? I will then close this PR @ram1123.

**Comment by vukasinmilosevic** [comment]
@tjavaid I see that there are 710 files changed. You didn't start from the CMS_10_X branch as base but instead started from some really old version. Can you please open a new PR, starting from CMS_10_X with your additions? I will then close this PR @ram1123.

**Comment by vukasinmilosevic** [comment]
Closing this pull request as there is no way this can be merged @ram1123 @tjavaid

**Pull request closed without merging**
