### PR TITLE
Adding initial implementation of the double differential measurement for the efficiency module

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
Added a new function for reading the bin choices:
* ```python/read_bins.py``` has support for our standard bin input ```|100|140|``` for 1d measurement as well as new features for double differential measurement 
* Added support for ```|0|1|10| vs |20|30|50| / |20|35|40|50|``` binning input, where each bin of variable 1 is assigned a different binning scheme of variable 2
* Added support for ```|20|30| vs |30|35| / |20|30| vs |35|50|``` binning input, where we specify each 2d bin with the exact boundaries, needed for custom bins, like the ones found for ```massZ1 vs massZ2```
* **To be added:** Support for for single 2D bin, i.e. ```|20|30| vs |30|35| ``` - we don't need it for the measurement, as there are no such bins, but it would be good to add it for code reusability.
*  Added the treatment for bins that contain ```'inf'``` in them.

Most of the changes are related to the efficiency module:
* Adding initial implementation of the double differential measurement for the efficiency module
* Commenting on each selection step for better understanding
* Variable names for the double differential measurement are expected to be separated with ``` vs ``` in the input ```string```, i.e. ```massZ1 vs massZ2```
* Added several initialisations for variables as some variables were unprotected and could crash.

Updated the ```getUnc_Unc.py```:
* It now supports the double differential measurement input in the same vein as the efficiency module - note: for all variable but for nJets - we need to understand the difference between two modules (```getUnc_nJets_Unc.py```) before proceeding.
* Added the treatment for bins that contain ```'inf'``` in them.

Minor fixes include the addition of missing files mentioned in #17 and @ram1123 's previous PR.

### CODE REVIEW

**Comment by vukasinmilosevic** [comment]
From my side the PR is complete (@ram1123, @qyguo). The additional cut option and the merging of Njets uncertainty module will be added after we discuss with the team. 

For ease of starting testing, here are two examples of commands to quickly run the new additions:

```
python -u efficiencyFactors.py -l -q -b --obsName="massZ1 vs massZ2" --obsBins="|50|80| vs |10|30| / |50|80| vs |30|inf|" -c "4e"
python -u getUnc_Unc.py -l -q -b --obsName="massZ1 vs massZ2" --obsBins="|50|80| vs |10|30| / |50|80| vs |30|inf|"
```

**Comment by ram1123** [comment]
Seem fine... I run the mass4l and one 2D variable. And it worked without any issue.

Also, for 1D mass4l I tried to match the efficiency output dict with the older one. Both are same.

**Comment by vukasinmilosevic** [comment]
Nice. Is the same valid for the Uncertainty module?

**Comment by ram1123** [comment]
> Nice. Is the same valid for the Uncertainty module?

yes.

**Comment by vukasinmilosevic** [comment]
Perfect!

**Pull request merged**
